apiVersion: v1
kind: Service
metadata:
  name: llama-svc
  namespace: llmgw
spec:
  selector:
    app: llama-server
  ports:
  - name: chat
    port: 8080
    targetPort: chat
  - name: embed
    port: 8081
    targetPort: embed
  clusterIP: None
